FROM python:3.8.0-slim-buster

WORKDIR /ebook_automation

RUN apt-get update && \
    apt-get install -y zip unzip epubcheck

RUN rm -rf /var/cache/apt/*

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flake8==3.7.7

COPY run ./
COPY ./src/ ./src/

RUN flake8 ./src/

CMD bash run epub_file
