#!/bin/bash

set -eu

FORCE_CHECK=0

for arg in "$@"
do
    case $arg in
        -c|--check)
            FORCE_CHECK=1
            shift
            ;;
    esac
done

book_name=$1
source_dir=$(mktemp -d -t obp-epub-fixup-src-XXXXXX)
target_dir=$(mktemp -d -t obp-epub-fixup-trg-XXXXXX)

cleanup () {
    local rv=$?
    rm -rf -- "$source_dir" "$target_dir"
    exit $rv
}

trap cleanup EXIT

check_epub () {
    epubcheck -q ${book_name}_new.epub &> ${book_name}_new.log
    local err=$?

    if [ $err -ne 0 ]; then
	echo "[ERROR] Epubckeck reported errors, ${book_name}_new.log produced"

    elif [ $err -eq 0 ] && [ -f ${book_name}_new.log ]; then
	echo "[WARNING] Epubcheck issued warning messages, ${book_name}_new.log produced"

    fi
}

pack_epub () {
    cd ${target_dir}
    zip -qX0 ${book_name}_new.epub mimetype
    zip -qXr ${book_name}_new.epub META-INF/ \
                                   OEBPS/
}

cd $(dirname $0)

# echo "Unzip epub document"
unzip -q ${book_name}.epub -d ${source_dir}
unzip -q ${book_name}.epub -d ${target_dir}

# echo "Fix toc.xhtml"
python3 src/fix_toc_xhtml.py ${source_dir}/OEBPS/toc.xhtml \
                             ${target_dir}/OEBPS/toc.xhtml

# echo "Fix toc.ncx"
python3 src/fix_toc_ncx.py ${target_dir}/OEBPS/toc.xhtml \
                           ${source_dir}/OEBPS/toc.ncx \
                           ${target_dir}/OEBPS/toc.ncx

# echo "Fix title tags in book sections"
python3 src/fix_title_tag.py ${target_dir}/OEBPS/toc.xhtml \
                             ${source_dir}/OEBPS/ \
                             ${target_dir}/OEBPS/

# echo "Create new epub file" 
(pack_epub)

# echo "Copy epub file back"
cp ${target_dir}/${book_name}_new.epub .

if [ $FORCE_CHECK -eq 1 ]; then
    # echo "Check epub for errors"
    check_epub
fi
