#!/bin/bash

set -eu

book_name=$1
source_dir=$(mktemp -d -t obp-epub-fixup-src-XXXXXX)
target_dir=$(mktemp -d -t obp-epub-fixup-trg-XXXXXX)

cleanup () {
    local rv=$?
    rm -rf -- "$source_dir" "$target_dir"
    exit $rv
}

trap cleanup EXIT

pack_epub () {
    cd ${target_dir}
    zip -X0 ${book_name}_new.epub mimetype
    zip -Xr ${book_name}_new.epub META-INF/ \
                                  OEBPS/
}

cd $(dirname $0)

echo "Unzip epub document"
unzip -q ${book_name}.epub -d ${source_dir}
unzip -q ${book_name}.epub -d ${target_dir}

echo "Fix toc.xhtml"
python3 src/fix_toc_xhtml.py ${source_dir}/OEBPS/toc.xhtml \
                             ${target_dir}/OEBPS/toc.xhtml

echo "Fix toc.ncx"
python3 src/fix_toc_ncx.py ${target_dir}/OEBPS/toc.xhtml \
                           ${source_dir}/OEBPS/toc.ncx \
                           ${target_dir}/OEBPS/toc.ncx

echo "Create new epub file" 
(pack_epub)

echo "Copy epub file back"
cp ${target_dir}/${book_name}_new.epub .
