#!/bin/bash

set -eu

book_name=$1
source_dir=$(mktemp -d -t obp-epub-fixup-src-XXXXXX)
target_dir=$(mktemp -d -t obp-epub-fixup-trg-XXXXXX)

cleanup () {
    local rv=$?
    rm -rf -- "$source_dir" "$target_dir"
    exit $rv
}

trap cleanup EXIT

cd $(dirname $0)

echo "Unzip epub document"
unzip -q ${book_name}.epub -d ${source_dir}
unzip -q ${book_name}.epub -d ${target_dir}

echo "Fix toc.xhtml"
python3 src/fix_toc_xhtml.py ${source_dir}/OEBPS/toc.xhtml \
                             ${target_dir}/OEBPS/toc.xhtml
